import { test, expect, type Page } from '@playwright/test';
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
}
test('complete multilingual Demo Day flow, timers, parallel work, AI failure and reset', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Что будем готовить сегодня?');
  await noOverflow(page);
  await page.getByRole('button', { name: 'KZ', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Бүгін не пісіреміз?');
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('What are we cooking today?');
  await page.reload();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('What are we cooking today?');
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-home.png`, fullPage: true });
  await page.getByRole('button', { name: 'Start cooking', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Continue', exact: true })).toBeDisabled();
  const selectors = page.locator('.select-button');
  await selectors.nth(0).click();
  await expect(page.getByRole('button', { name: 'Continue', exact: true })).toBeDisabled();
  await selectors.nth(1).click(); await selectors.nth(2).click();
  await page.getByRole('button', { name: 'KZ', exact: true }).click();
  await expect(page.locator('.recipe-card.is-selected')).toHaveCount(3);
  await page.getByRole('button', { name: 'Жалғастыру', exact: true }).click();
  await noOverflow(page);
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-planner.png`, fullPage: true });
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await page.getByLabel('When should everything be ready?').fill('19:30');
  await page.getByRole('button', { name: 'Decrease: Pans', exact: true }).click();
  await page.getByRole('button', { name: 'Create plan', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Not enough equipment');
  await page.getByRole('button', { name: 'Increase: Pans', exact: true }).click();
  await page.getByRole('button', { name: 'Create plan', exact: true }).click();
  await expect(page.locator('.timeline-row')).toHaveCount(13);
  await noOverflow(page);
  const times = await page.locator('.timeline-time').allTextContents();
  await page.getByRole('button', { name: 'KZ', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Жоспар дайын');
  expect(await page.locator('.timeline-time').allTextContents()).toEqual(times.map(value => value.replaceAll('min', 'мин')));
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-schedule.png`, fullPage: true });
  await page.getByRole('button', { name: 'Start now', exact: true }).click();
  const currentTask = await page.locator('.current-card h2').textContent();
  const timer = page.locator('.current-card [role="timer"]');
  const initialTimer = await timer.textContent();
  await expect.poll(() => timer.textContent()).not.toBe(initialTimer);
  await page.getByRole('button', { name: 'KZ', exact: true }).click();
  await expect(page.locator('.session-progress strong')).toHaveText('0 / 13');
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.locator('.current-card h2')).toHaveText(currentTask!);
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page.locator('.parallel-task')).not.toHaveCount(0);
  await noOverflow(page);
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-cooking.png`, fullPage: true });
  await page.getByRole('button', { name: 'Ask Culinex AI', exact: true }).click();
  await noOverflow(page);
  await page.getByLabel('Your question', { exact: true }).fill('What can I use instead of cream?');
  const responsePromise = page.waitForResponse('**/api/ai');
  await page.getByRole('button', { name: 'Ask', exact: true }).click();
  const response = await responsePromise; expect(response.status()).toBe(503);
  await expect(page.getByRole('alert')).toContainText('temporarily unavailable');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(page.locator('.session-progress strong')).toHaveText('2 / 13');
  await page.getByRole('button', { name: 'Show full plan', exact: true }).click();
  await expect(page.locator('.timeline-row.finished')).toHaveCount(2);
  await page.getByRole('button', { name: 'Hide plan', exact: true }).click();
  for (let i = 2; i < 13; i++) await page.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Dinner is ready');
  await expect(page.locator('.result-stats')).toContainText('13 / 13');
  await page.getByRole('button', { name: 'RU', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Ужин готов');
  await page.getByRole('button', { name: 'KZ', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Кешкі ас дайын');
  await expect(page.locator('.result-dishes > div')).toHaveCount(3);
  await noOverflow(page);
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-result.png`, fullPage: true });
  await page.getByRole('button', { name: 'Аяқтау', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Бүгін не пісіреміз?');
  await page.getByRole('button', { name: 'Пісіруді бастау', exact: true }).click();
  await expect(page.locator('.recipe-card.is-selected')).toHaveCount(0);
  expect(errors).toEqual([]);
});
test('AI receives current language and context; reopening clears the previous response', async ({ page }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'EN', exact: true }).click();
  await page.getByRole('button', { name: 'Start cooking', exact: true }).click();
  await page.locator('.select-button').nth(0).click(); await page.locator('.select-button').nth(1).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Create plan', exact: true }).click();
  await page.getByRole('button', { name: 'Start now', exact: true }).click();
  await page.route('**/api/ai', async route => {
    const data = route.request().postDataJSON();
    expect(data.language).toBe('kk'); expect(data.context.selectedRecipes).toHaveLength(2);
    expect(data.context.currentTask).not.toBe('');
    await route.fulfill({ json: { answer: 'Қою болса, аздап су қосыңыз.', language: 'kk' } });
  });
  await page.getByRole('button', { name: 'KZ', exact: true }).click();
  await page.getByRole('button', { name: 'Culinex AI-дан сұрау', exact: true }).click();
  await page.getByLabel('Сұрағыңыз', { exact: true }).fill('Тұздық қою болса не істеймін?');
  await page.getByRole('button', { name: 'Сұрау', exact: true }).click();
  await expect(page.locator('.ai-answer')).toHaveText('Қою болса, аздап су қосыңыз.');
  await page.getByRole('button', { name: 'Жабу', exact: true }).click();
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await page.getByRole('button', { name: 'Ask Culinex AI', exact: true }).click();
  await expect(page.locator('.ai-answer')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.session-progress strong')).toHaveText('0 / 9');
});
